Events
yayner2002/reactcalculatorapp pull request #5
Opened 2022-08-02 14:46 UTC by yayner2002

in this PR, the following activities were done.

- Handle events in a React app.
- Use React life cycle methods.
- Understand the mechanism of lifting the state up.

2022-08-02 15:40 UTC, DeliceLydia requested changes
## Hi @yayner2002, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project are:
- Awesome README
- Followed git workflow


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-02 15:40 UTC, DeliceLydia commented on src/components/Calculator.js
> +              %
- [ ] This should be `modulus` not `division`

2022-08-02 18:03 UTC, yayner2002 commented on src/components/Calculator.js
> +              %
hi, @DeliceLydia I didn't get your comment. please make some clarification on this particular line of code. 👍

2022-08-02 18:18 UTC, DeliceLydia commented on src/components/Calculator.js
> +              %
Hello @yayner2002, `%` should be modulus which means It should return the remainder of two integers that have been divided

2022-08-02 18:26 UTC, yayner2002 commented on src/components/Calculator.js
> +              %
hi @DeliceLydia  yeah, it does what you are saying. I don't know if you have checked it. e.g.9%3 = 0 not 3 right ?

2022-08-02 19:00 UTC, yayner2002 commented on src/components/Calculator.js
> +              %
hi, @DeliceLydia  are you still confused, I mean do I need to explain it further?

2022-08-03 08:13 UTC, mikethreels approved these changes
Hi Yayner, 

The modulus is working as expected on my side, Good job trying to clarify.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 08:17 UTC, merged